import { TabWidget , VerticalBox, GroupBox, LineEdit, Button} from "std-widgets.slint";
import { Constants } from "./constants.slint";
import { SortTabView, Sorting } from "./sort_tab.slint";
import { ScrapeTabView } from "./scrape_tab.slint";

export { Sorting }

export component RetroTetanus inherits Window {
	title: "Retro Tetanus";
	preferred-width: 800px;
	preferred-height: 600px;


	VerticalLayout {
		width: root.width;
		spacing: Constants.pad-amount;
		padding-bottom: Constants.pad-amount;

		TabWidget {
			width: 100%;
			Tab {
				title: "Sort";
				SortTabView {}
			}
			Tab {
				title: "Scrape";
				ScrapeTabView {}
			}
		}

		hint-box := Text {
			x: Constants.pad-amount;
			text: "Hints will appear here...";
		}
	}
}
