import { TabWidget , VerticalBox, GroupBox, LineEdit, Button, StandardTableView} from "std-widgets.slint";
import { Constants } from "./constants.slint";

export global Sorting {
	callback get-source-path();
	callback get-dest-path();
	in-out property <string> source-path;
	in-out property <string> dest-path;
}

export component SortTabView inherits Rectangle {
	// background: brown;
	callback choose-source-path <=> source-path-button.clicked;

	VerticalBox {
		HorizontalLayout {
			spacing: Constants.pad-amount;
			source-path-button := Button { clicked => { Sorting.get-source-path(); } }
			LineEdit { 
				placeholder-text: "Path to your ROMs...";
				text: Sorting.source-path;
				enabled: false;
			}
		}
		HorizontalLayout {
			spacing: Constants.pad-amount;
			dest-path-button := Button { clicked => { Sorting.get-dest-path(); }}
			LineEdit { 
				placeholder-text: "Path where your ROMs go...";
				text: Sorting.dest-path;
				enabled: false;
			}
		}

		StandardTableView { 
			columns: [
				{title: "File"},
				{title: "Path"},
				{title: "ROM"},
				{title: "Console"},
				{title: "Region"},
			];
			rows: [];
		 }

		Text {
			text: "Placeholder A";
		}
		
		// Filler rectangle
		// Rectangle {
		// 	background: darkred;
		// }
	}
}
